services:
  postgres-objects-2024:
    image: postgres:latest
    container_name: object-database-1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=object_1
    ports:
      - "5433:5432"
    restart: unless-stopped
  
  postgres-objects-2025:
    image: postgres:latest
    container_name: object-database-2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=object_2
    ports:
      - "5434:5432"
    restart: unless-stopped  